load("@rules_python//python:defs.bzl", "py_binary", "py_library")

package(default_visibility = [
    "//purrf/google:__pkg__",
    "//tests/google:__pkg__",
])

py_library(
    name = "authentication_utils",
    srcs = [
        "authentication_utils.py",
        "constants.py",
    ],
    deps = [
        "//tools/log",
        "@pypi//google_api_python_client",
        "@pypi//google_auth_oauthlib",
        "@pypi//google_cloud_pubsub",
    ],
)

py_library(
    name = "chat_utils",
    srcs = [
        "chat_utils.py",
        "constants.py",
    ],
    deps = [
        "//tools/log",
    ],
)

py_library(
    name = "fetch_history_chat_message",
    srcs = [
        "constants.py",
        "fetch_history_chat_message.py",
    ],
    deps = [
        ":authentication_utils",
        ":chat_utils",
        "//redis_dal:redis_utils",
        "//tools/log",
    ],
)

py_binary(
    name = "google_api",
    srcs = ["google_api.py"],
    deps = [
        "fetch_history_chat_message",
        ":authentication_utils",
        ":chat_utils",
        "//tools/global_handle_exception:exception_handler",
        "//tools/log",
        "@pypi//flask",
    ],
)

py_library(
    name = "pubsub_publisher",
    srcs = [
        "pubsub_publisher.py",
        "//google:authentication_utils",
    ],
    deps = [
        "//tools/log",
        "@pypi//google_api_python_client",
        "@pypi//google_cloud_pubsub",
    ],
)